### ISSUE TITLE
Consider using ruff to speed up pep8 checks

### ISSUE THREAD

**Issue by adamltyson** [SainsburyWellcomeCentre/python-cookiecutter#10]
https://github.com/charliermarsh/ruff

**Comment by adamltyson** [comment]
Also supports `pyproject.toml`

**Comment by adamltyson** [comment]
https://pypi.org/project/flake8-to-ruff/

**Comment by JoeZiminski** [comment]
This looks really nice, will try it out

**Comment by adamltyson** [comment]
https://github.com/charliermarsh/ruff-pre-commit

**Comment by dstansby** [comment]
I think this can be closed as completed.
