### ISSUE TITLE
Readme change

### ISSUE THREAD

**Issue by HernandoMV** [SainsburyWellcomeCentre/python-cookiecutter#23]
`git init -b main`  gives error in version 2.7.4

did this instead:
`git init`
`git checkout -b main` 

maybe is good to add it to readme.
Also, explicit instructions for how to install cookiecutter:
`pip install cookiecutter`

**Comment by adamltyson** [comment]
@HernandoMV is this issue arising just because an old version of Git doesn't support the newer syntax?

**Comment by HernandoMV** [comment]
I think so. I haven't tried to update git though
