### ISSUE TITLE
dependencies not in .toml file

### ISSUE THREAD

**Issue by HernandoMV** [SainsburyWellcomeCentre/python-cookiecutter#24]
Project was created without dependencies line in .toml
Maybe it would be unclear to people where to put them w/o an example. Add numpy maybe as default?

**Comment by adamltyson** [comment]
Good catch, thanks @HernandoMV!

@SainsburyWellcomeCentre/neuroinformatics-unit any thoughts here? It seems bad practice to have an empty dependencies section (and to add a potentially unused dependency). Should we just add a (fairly prominant) section to the readme showing people how to add dependencies to their project?

**Comment by JoeZiminski** [comment]
that is a nice idea to have an example section, although agree about empty and unused dependencies. Would it be possible to add a section to the cookiecutter introduction - "would you like to add an example dependencies section to your pyproject.toml file?" or something similar
