### ISSUE TITLE
Sudden error with 'pip-shims' causing failure during Actions workflow

### ISSUE THREAD

**Issue by raacampbell** [SainsburyWellcomeCentre/python-cookiecutter#45]
Forgive me if this is not the right place for this question, but the GitHub actions workflow suddenly started failing on me and the error seems to suggest a problem with the TOML file. 
[https://github.com/Zapit-Optostim/zapit-Python-Bridge/actions/runs/4193091401/jobs/7269521942](https://github.com/Zapit-Optostim/zapit-Python-Bridge/actions/runs/4193091401/jobs/7269521942)
I have not altered it recently other than to change max line lengths. 

The specific error is:
```
RuntimeError: The Poetry configuration is invalid:
 - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
```

I Googled a bit and looks like maybe [some packages have different behaviors now](https://levelup.gitconnected.com/fix-runtimeerror-poetry-isort-5db7c67b60ff) and may require some extra sections in the TOML. I [tried adding these as empty sections](https://github.com/Zapit-Optostim/zapit-Python-Bridge/commit/864330eeeef4eab2f43a8492740c34fec2e94a68) but that did not help. Do you guys have any ideas?

**Comment by adamltyson** [comment]
I don't think this has anything to do with poetry (I spent a while trying to debug this). I've raised a PR (https://github.com/Zapit-Optostim/zapit-Python-Bridge/pull/5) which updates the `pre-commit` config, and (at least in my repo) fixes the issue.
