### ISSUE TITLE
Consider using both bump2version and setuptool_scm

### ISSUE THREAD

**Issue by adamltyson** [SainsburyWellcomeCentre/python-cookiecutter#5]
An excellent idea from @dstansby:

> maybe a good way to go would be to use both, and use bump2version to just set the git tag correctly, with setuptools_scm handling setting the Python package version from the git tag?

We should test this. In theory this should allow for the nice bits of `bump2version` such as being able to set the version semantically rather than numerically, but without the complex setup to define what gets updated and where.

This should also hopefully future proof us a bit to changes in python packaging. 

cc @SainsburyWellcomeCentre/neuroinformatics-unit

**Comment by niksirbi** [comment]
That sounds like a great idea if it actually works in practice, without the two tools clashing

**Comment by JoeZiminski** [comment]
Interesting discussion on this [here](https://github.com/21cmfast/21cmFAST/issues/175), in the end I believe they have also taken this joint approach.

**Comment by adamltyson** [comment]
Now gone with only `setuptools_scm`. Need to document this (and remove the `bump2version` docs).

**Comment by adamltyson** [comment]
`setuptools_scm` is now documented
